// This is a small, audited intake for important recent findings that may not
// appear in a short ranked database search. Entries must be linked to a
// public primary paper and, when available, an authoritative research source.
const ipfModelSignal = ({
  id,
  title,
  journal,
  year,
  pmid,
  doi,
  candidate,
  summary,
  relationEvidence,
  aiIdeaPriority,
}) => ({
  id,
  conditionAliases: ['idiopathic pulmonary fibrosis', 'ipf'],
  title,
  url: `https://pubmed.ncbi.nlm.nih.gov/${pmid}/`,
  type: 'Preclinical research study',
  origin: 'PubMed',
  journal,
  year,
  pmid,
  doi,
  summary,
  conditionScope: 'related-preclinical',
  conditionScopeLabel: 'lung-fibrosis animal or lab models',
  relatedConditionContext: 'This was animal or lab research on lung fibrosis, not a study in people with idiopathic pulmonary fibrosis.',
  aiIdeaPriority,
  candidateLeads: [{
    name: candidate,
    category: 'Early animal or lab research',
    roleVerified: true,
    sourceEarlyResearchDerived: true,
    relationship: 'condition-family-preclinical',
    relationEvidence,
  }],
  aiEligible: false,
})

const RECENT_RESEARCH_SIGNALS = [
  {
    id: 'rp-erucamide-retinal-protection-study-2026',
    conditionAliases: ['retinitis pigmentosa', 'rp'],
    title: 'A fatty acid amide activates myeloid cells and improves neurovascular outcomes in retinal degeneration',
    url: 'https://pubmed.ncbi.nlm.nih.gov/42321469/',
    type: 'Preclinical research study',
    origin: 'Nature Neuroscience',
    journal: 'Nature Neuroscience',
    year: '2026',
    pmid: '42321469',
    doi: '10.1038/s41593-026-02341-w',
    summary: 'This paper studied erucamide in mouse models of retinal degeneration, including a model related to retinitis pigmentosa. It was not a study in people with retinitis pigmentosa.',
    conditionScope: 'related-preclinical',
    conditionScopeLabel: 'related retinal-degeneration models',
    relatedConditionContext: 'Retinitis pigmentosa is an inherited retinal disease. This source is from a related retinal-degeneration model, not a study in people with retinitis pigmentosa.',
    supportingSourceIds: ['rp-nei-erucamide-retinal-protection-2026'],
    aiIdeaPriority: 100,
    candidateLeads: [
      {
        name: 'Erucamide',
        category: 'Early animal or lab research',
        roleVerified: true,
        sourceEarlyResearchDerived: true,
        relationship: 'condition-family-preclinical',
        relationEvidence: 'In vivo delivery of erucamide limited vascular and neuronal degeneration in retinal disease models.',
      },
    ],
    // The card is built deterministically from the audited source. It is not
    // sent to the prose-writing model, which prevents a model from turning it
    // into a patient-accessible treatment claim.
    aiEligible: false,
  },
  {
    id: 'rp-nei-erucamide-retinal-protection-2026',
    conditionAliases: ['retinitis pigmentosa', 'rp'],
    title: 'NEI-funded research identifies molecule that strengthens the eye\'s response to damage in retinal disease',
    url: 'https://www.nei.nih.gov/research-and-training/research-news/nei-funded-research-identifies-molecule-strengthens-eyes-response-damage-retinal-disease',
    type: 'NIH research news',
    origin: 'National Eye Institute',
    year: '2026',
    summary: 'The National Eye Institute describes this as preclinical retinal-degeneration research. It is not a human treatment study for retinitis pigmentosa.',
    conditionScope: 'related-preclinical',
    conditionScopeLabel: 'related retinal-degeneration models',
    relatedConditionContext: 'Retinitis pigmentosa is an inherited retinal disease. This source is from a related retinal-degeneration model, not a study in people with retinitis pigmentosa.',
    aiEligible: false,
  },
  {
    id: 'rp-melatonin-rd10-2017',
    conditionAliases: ['retinitis pigmentosa', 'rp'],
    title: 'Melatonin delays photoreceptor degeneration in a mouse model of autosomal recessive retinitis pigmentosa',
    url: 'https://pubmed.ncbi.nlm.nih.gov/28580724/',
    type: 'Preclinical research study',
    origin: 'PubMed',
    journal: 'Journal of Pineal Research',
    year: '2017',
    pmid: '28580724',
    doi: '10.1111/jpi.12428',
    summary: 'In an rd10 mouse model of retinitis pigmentosa, melatonin delayed photoreceptor loss. This was an animal study, not a study in people.',
    conditionScope: 'related-preclinical',
    conditionScopeLabel: 'retinitis-pigmentosa animal models',
    relatedConditionContext: 'This was an animal model of retinitis pigmentosa, not a human treatment study.',
    aiIdeaPriority: 95,
    candidateLeads: [{ name: 'Melatonin', category: 'Early animal or lab research', roleVerified: true, sourceEarlyResearchDerived: true, relationship: 'condition-family-preclinical', relationEvidence: 'Melatonin delays photoreceptor degeneration in a mouse model of autosomal recessive retinitis pigmentosa.' }],
    aiEligible: false,
  },
  {
    id: 'rp-sulforaphane-rd10-2022',
    conditionAliases: ['retinitis pigmentosa', 'rp'],
    title: 'Sulforaphane Modulates the Inflammation and Delays Neurodegeneration on a Retinitis Pigmentosa Mice Model',
    url: 'https://pubmed.ncbi.nlm.nih.gov/35300301/',
    type: 'Preclinical research study',
    origin: 'PubMed',
    journal: 'International Journal of Molecular Sciences',
    year: '2022',
    pmid: '35300301',
    summary: 'In rd10 mice, sulforaphane delayed photoreceptor loss and changed inflammatory signals. This was an animal study, not a study in people.',
    conditionScope: 'related-preclinical',
    conditionScopeLabel: 'retinitis-pigmentosa animal models',
    relatedConditionContext: 'This was an animal model of retinitis pigmentosa, not a human treatment study.',
    aiIdeaPriority: 94,
    candidateLeads: [{ name: 'Sulforaphane', category: 'Early animal or lab research', roleVerified: true, sourceEarlyResearchDerived: true, relationship: 'condition-family-preclinical', relationEvidence: 'Sulforaphane modulates inflammation and delays neurodegeneration in a retinitis pigmentosa mice model.' }],
    aiEligible: false,
  },
  {
    id: 'rp-tudca-rd10-2008',
    conditionAliases: ['retinitis pigmentosa', 'rp'],
    title: 'Tauroursodeoxycholic acid preservation of photoreceptor structure and function in the rd10 mouse through postnatal day 30',
    url: 'https://pubmed.ncbi.nlm.nih.gov/18436848/',
    type: 'Preclinical research study',
    origin: 'PubMed',
    journal: 'Investigative Ophthalmology & Visual Science',
    year: '2008',
    pmid: '18436848',
    summary: 'Tauroursodeoxycholic acid preserved photoreceptor structure and function in rd10 mice. This was an animal study, not a study in people.',
    conditionScope: 'related-preclinical',
    conditionScopeLabel: 'retinitis-pigmentosa animal models',
    relatedConditionContext: 'This was an animal model of retinitis pigmentosa, not a human treatment study.',
    aiIdeaPriority: 93,
    candidateLeads: [{ name: 'Tauroursodeoxycholic acid (TUDCA)', category: 'Early animal or lab research', roleVerified: true, sourceEarlyResearchDerived: true, relationship: 'condition-family-preclinical', relationEvidence: 'Tauroursodeoxycholic acid preserved photoreceptor structure and function in the rd10 mouse.' }],
    aiEligible: false,
  },
  {
    id: 'rp-minocycline-rds-2004',
    conditionAliases: ['retinitis pigmentosa', 'rp'],
    title: 'Minocycline delays photoreceptor death in the rds mouse through a microglia-independent mechanism',
    url: 'https://pubmed.ncbi.nlm.nih.gov/15109914/',
    type: 'Preclinical research study',
    origin: 'PubMed',
    journal: 'Experimental Eye Research',
    year: '2004',
    pmid: '15109914',
    doi: '10.1016/j.exer.2004.02.002',
    summary: 'Minocycline delayed photoreceptor cell death in an rds mouse model. This was an animal study, not a study in people.',
    conditionScope: 'related-preclinical',
    conditionScopeLabel: 'retinitis-pigmentosa animal models',
    relatedConditionContext: 'This was an animal model of retinitis pigmentosa, not a human treatment study.',
    aiIdeaPriority: 92,
    candidateLeads: [{ name: 'Minocycline', category: 'Early animal or lab research', roleVerified: true, sourceEarlyResearchDerived: true, relationship: 'condition-family-preclinical', relationEvidence: 'Minocycline delays photoreceptor death in the rds mouse.' }],
    aiEligible: false,
  },
  {
    id: 'rp-kus121-animal-models-2016',
    conditionAliases: ['retinitis pigmentosa', 'rp'],
    title: 'Neuoroprotective efficacies by KUS121, a VCP modulator, on animal models of retinal degeneration',
    url: 'https://pubmed.ncbi.nlm.nih.gov/27503804/',
    type: 'Preclinical research study',
    origin: 'PubMed',
    journal: 'Scientific Reports',
    year: '2016',
    pmid: '27503804',
    summary: 'KUS121 protected photoreceptors in retinal-degeneration animal models, including models linked to inherited retinal disease. This was not a human treatment study.',
    conditionScope: 'related-preclinical',
    conditionScopeLabel: 'related retinal-degeneration animal models',
    relatedConditionContext: 'This was retinal-degeneration animal research, not a human treatment study for retinitis pigmentosa.',
    aiIdeaPriority: 88,
    candidateLeads: [{ name: 'KUS121', category: 'Early animal or lab research', roleVerified: true, sourceEarlyResearchDerived: true, relationship: 'condition-family-preclinical', relationEvidence: 'KUS121 effectively protects photoreceptors in two animal models of retinal degeneration.' }],
    aiEligible: false,
  },
  {
    id: 'rp-piceid-octanoate-rd10-2024',
    conditionAliases: ['retinitis pigmentosa', 'rp'],
    title: 'Synthesis and Evaluation of Glucosyl-, Acyl- and Silyl- Resveratrol Derivatives as Retinoprotective Agents: Piceid Octanoate Notably Delays Photoreceptor Degeneration in a Retinitis Pigmentosa Mouse Model',
    url: 'https://pubmed.ncbi.nlm.nih.gov/39598393/',
    type: 'Preclinical research study',
    origin: 'PubMed',
    journal: 'International Journal of Molecular Sciences',
    year: '2024',
    pmid: '39598393',
    summary: 'Piceid octanoate delayed photoreceptor degeneration in an rd10 mouse model. This was an animal study, not a study in people.',
    conditionScope: 'related-preclinical',
    conditionScopeLabel: 'retinitis-pigmentosa animal models',
    relatedConditionContext: 'This was an animal model of retinitis pigmentosa, not a human treatment study.',
    aiIdeaPriority: 90,
    candidateLeads: [{ name: 'Piceid octanoate', category: 'Early animal or lab research', roleVerified: true, sourceEarlyResearchDerived: true, relationship: 'condition-family-preclinical', relationEvidence: 'Piceid octanoate notably delays photoreceptor degeneration in a retinitis pigmentosa mouse model.' }],
    aiEligible: false,
  },
  {
    id: 'rp-curcumin-pro23his-2015',
    conditionAliases: ['retinitis pigmentosa', 'rp'],
    title: 'Prenatal Exposure to Curcumin Protects Rod Photoreceptors in a Transgenic Pro23His Swine Model of Retinitis Pigmentosa',
    url: 'https://pubmed.ncbi.nlm.nih.gov/26396931/',
    type: 'Preclinical research study',
    origin: 'PubMed',
    journal: 'Translational Vision Science & Technology',
    year: '2015',
    pmid: '26396931',
    doi: '10.1167/tvst.4.5.5',
    summary: 'Curcumin was studied in a transgenic swine model of retinitis pigmentosa. This was an animal study, not a study in people.',
    conditionScope: 'related-preclinical',
    conditionScopeLabel: 'retinitis-pigmentosa animal models',
    relatedConditionContext: 'This was an animal model of retinitis pigmentosa, not a human treatment study.',
    aiIdeaPriority: 91,
    candidateLeads: [{ name: 'Curcumin', category: 'Early animal or lab research', roleVerified: true, sourceEarlyResearchDerived: true, relationship: 'condition-family-preclinical', relationEvidence: 'Prenatal exposure to curcumin protects rod photoreceptors in a transgenic retinitis pigmentosa swine model.' }],
    aiEligible: false,
  },
  {
    id: 'rp-ibuprofen-light-damage-2025',
    conditionAliases: ['retinitis pigmentosa', 'rp'],
    title: 'Ibuprofen reduces inflammation, necroptosis and protects photoreceptors from light-induced retinal degeneration',
    url: 'https://pubmed.ncbi.nlm.nih.gov/39875939/',
    type: 'Preclinical research study',
    origin: 'PubMed',
    journal: 'Cell Death Discovery',
    year: '2025',
    pmid: '39875939',
    summary: 'Ibuprofen protected photoreceptors in a mouse model of light-induced retinal degeneration. This was not a study in people with retinitis pigmentosa.',
    conditionScope: 'related-preclinical',
    conditionScopeLabel: 'related retinal-degeneration animal models',
    relatedConditionContext: 'This was retinal-degeneration animal research, not a human treatment study for retinitis pigmentosa.',
    aiIdeaPriority: 89,
    candidateLeads: [{ name: 'Ibuprofen', category: 'Early animal or lab research', roleVerified: true, sourceEarlyResearchDerived: true, relationship: 'condition-family-preclinical', relationEvidence: 'Ibuprofen protects photoreceptors from light-induced retinal degeneration.' }],
    aiEligible: false,
  },
  {
    id: 'rp-thx-b-rd10-rhop-2017',
    conditionAliases: ['retinitis pigmentosa', 'rp'],
    title: 'p75NTR antagonists attenuate photoreceptor cell loss in murine models of retinitis pigmentosa',
    url: 'https://pubmed.ncbi.nlm.nih.gov/28703796/',
    type: 'Preclinical research study',
    origin: 'PubMed',
    journal: 'Cell Death & Disease',
    year: '2017',
    pmid: '28703796',
    summary: 'THX-B, a p75NTR antagonist, protected photoreceptors in rd10 and RhoP mouse models. This was an animal study, not a study in people.',
    conditionScope: 'related-preclinical',
    conditionScopeLabel: 'retinitis-pigmentosa animal models',
    relatedConditionContext: 'This was an animal model of retinitis pigmentosa, not a human treatment study.',
    aiIdeaPriority: 87,
    candidateLeads: [{ name: 'THX-B', category: 'Early animal or lab research', roleVerified: true, sourceEarlyResearchDerived: true, relationship: 'condition-family-preclinical', relationEvidence: 'THX-B afforded neuroprotection to photoreceptor cells in rd10 and RhoP mouse models.' }],
    aiEligible: false,
  },
  {
    id: 'rp-mycophenolate-rd10-rd1-2020',
    conditionAliases: ['retinitis pigmentosa', 'rp'],
    title: 'Suppression of cGMP-Dependent Photoreceptor Cytotoxicity With Mycophenolate Is Neuroprotective in Murine Models of Retinitis Pigmentosa',
    url: 'https://pubmed.ncbi.nlm.nih.gov/32785677/',
    type: 'Preclinical research study',
    origin: 'PubMed',
    journal: 'Investigative Ophthalmology & Visual Science',
    year: '2020',
    pmid: '32785677',
    summary: 'Mycophenolate mofetil delayed photoreceptor loss in rd10 and rd1 mouse models. This was an animal study, not a study in people.',
    conditionScope: 'related-preclinical',
    conditionScopeLabel: 'retinitis-pigmentosa animal models',
    relatedConditionContext: 'This was an animal model of retinitis pigmentosa, not a human treatment study.',
    aiIdeaPriority: 86,
    candidateLeads: [{ name: 'Mycophenolate mofetil', category: 'Early animal or lab research', roleVerified: true, sourceEarlyResearchDerived: true, relationship: 'condition-family-preclinical', relationEvidence: 'Mycophenolate mofetil delayed retinal degeneration in rd10 and rd1 mouse models.' }],
    aiEligible: false,
  },
  {
    id: 'rp-myriocin-rd10-2010',
    conditionAliases: ['retinitis pigmentosa', 'rp'],
    title: 'Inhibition of ceramide biosynthesis preserves photoreceptor structure and function in a mouse model of retinitis pigmentosa',
    url: 'https://pubmed.ncbi.nlm.nih.gov/20937879/',
    type: 'Preclinical research study',
    origin: 'PubMed',
    journal: 'Proceedings of the National Academy of Sciences',
    year: '2010',
    pmid: '20937879',
    summary: 'Myriocin slowed photoreceptor loss in rd10 mice in this study. This was an animal study, not a study in people.',
    conditionScope: 'related-preclinical',
    conditionScopeLabel: 'retinitis-pigmentosa animal models',
    relatedConditionContext: 'This was an animal model of retinitis pigmentosa, not a human treatment study.',
    aiIdeaPriority: 85,
    candidateLeads: [{ name: 'Myriocin', category: 'Early animal or lab research', roleVerified: true, sourceEarlyResearchDerived: true, relationship: 'condition-family-preclinical', relationEvidence: 'Myriocin slowed photoreceptor loss in the rd10 mouse model.' }],
    aiEligible: false,
  },
  {
    id: 'rp-olaparib-rd1-2016',
    conditionAliases: ['retinitis pigmentosa', 'rp'],
    title: 'Olaparib significantly delays photoreceptor loss in a model for hereditary retinal degeneration',
    url: 'https://pubmed.ncbi.nlm.nih.gov/28004814/',
    type: 'Preclinical research study',
    origin: 'PubMed',
    journal: 'Cell Death & Disease',
    year: '2016',
    pmid: '28004814',
    summary: 'Olaparib delayed photoreceptor loss in rd1 mouse and retinal-explant research. This was not a study in people with retinitis pigmentosa.',
    conditionScope: 'related-preclinical',
    conditionScopeLabel: 'retinitis-pigmentosa animal and lab models',
    relatedConditionContext: 'This was animal and lab research related to retinitis pigmentosa, not a human treatment study.',
    aiIdeaPriority: 84,
    candidateLeads: [{ name: 'Olaparib', category: 'Early animal or lab research', roleVerified: true, sourceEarlyResearchDerived: true, relationship: 'condition-family-preclinical', relationEvidence: 'Olaparib reduced photoreceptor loss in an rd1 model for hereditary retinal degeneration.' }],
    aiEligible: false,
  },
  {
    id: 'rp-17aag-rp10-2010',
    conditionAliases: ['retinitis pigmentosa', 'rp'],
    title: 'Prevention of autosomal dominant retinitis pigmentosa by systemic drug therapy targeting heat shock protein 90 (Hsp90)',
    url: 'https://pubmed.ncbi.nlm.nih.gov/20817636/',
    type: 'Preclinical research study',
    origin: 'PubMed',
    journal: 'Human Molecular Genetics',
    year: '2010',
    pmid: '20817636',
    summary: 'The Hsp90 drug 17-AAG protected photoreceptors in an RP10 mouse model. This was an animal study, not a study in people.',
    conditionScope: 'related-preclinical',
    conditionScopeLabel: 'retinitis-pigmentosa animal models',
    relatedConditionContext: 'This was an animal model of retinitis pigmentosa, not a human treatment study.',
    aiIdeaPriority: 83,
    candidateLeads: [{ name: '17-AAG', category: 'Early animal or lab research', roleVerified: true, sourceEarlyResearchDerived: true, relationship: 'condition-family-preclinical', relationEvidence: '17-AAG protected photoreceptors in an autosomal-dominant retinitis pigmentosa mouse model.' }],
    aiEligible: false,
  },
  ipfModelSignal({
    id: 'ipf-tetrandrine-bleomycin-mouse-2021',
    title: 'Tetrandrine Modulates Rheb-mTOR Signaling-Mediated Selective Autophagy and Protects Pulmonary Fibrosis',
    journal: 'Frontiers in Pharmacology',
    year: '2021',
    pmid: '34880752',
    doi: '10.3389/fphar.2021.739220',
    candidate: 'Tetrandrine',
    summary: 'Tetrandrine was tested in bleomycin-treated mice and mouse lung fibroblasts. This was not a study in people with idiopathic pulmonary fibrosis.',
    relationEvidence: 'The study evaluated tetrandrine in bleomycin-induced mouse models and in mouse lung fibroblasts.',
    aiIdeaPriority: 100,
  }),
  ipfModelSignal({
    id: 'ipf-spermidine-bleomycin-mouse-2020',
    title: 'Spermidine attenuates bleomycin-induced lung fibrosis by inducing autophagy and inhibiting endoplasmic reticulum stress-induced cell death in mice',
    journal: 'Experimental & Molecular Medicine',
    year: '2020',
    pmid: '33318630',
    doi: '10.1038/s12276-020-00545-z',
    candidate: 'Spermidine',
    summary: 'Spermidine was tested in a bleomycin mouse model of lung fibrosis. This was not a study in people with idiopathic pulmonary fibrosis.',
    relationEvidence: 'Spermidine attenuated bleomycin-induced lung fibrosis in mice in this study.',
    aiIdeaPriority: 99,
  }),
  ipfModelSignal({
    id: 'ipf-celastrol-bleomycin-rat-2016',
    title: 'Celastrol enhances Nrf2 mediated antioxidant enzymes and exhibits anti-fibrotic effect through regulation of collagen production against bleomycin-induced pulmonary fibrosis',
    journal: 'Chemico-Biological Interactions',
    year: '2016',
    pmid: '26768587',
    doi: '10.1016/j.cbi.2016.01.006',
    candidate: 'Celastrol',
    summary: 'Celastrol was tested against bleomycin-induced pulmonary fibrosis in an experimental model. This was not a study in people with idiopathic pulmonary fibrosis.',
    relationEvidence: 'This paper tested celastrol in an experimental bleomycin model of pulmonary fibrosis.',
    aiIdeaPriority: 98,
  }),
  ipfModelSignal({
    id: 'ipf-andrographolide-bleomycin-2020',
    title: 'Andrographolide ameliorates bleomycin-induced pulmonary fibrosis by suppressing cell proliferation and myofibroblast differentiation of fibroblasts via the TGF-beta1-mediated Smad-dependent and -independent pathways',
    journal: 'Toxicology Letters',
    year: '2020',
    pmid: '31706003',
    doi: '10.1016/j.toxlet.2019.11.003',
    candidate: 'Andrographolide',
    summary: 'Andrographolide was tested in bleomycin lung-fibrosis research. This was not a study in people with idiopathic pulmonary fibrosis.',
    relationEvidence: 'The study reported andrographolide effects in a bleomycin pulmonary-fibrosis model.',
    aiIdeaPriority: 97,
  }),
  ipfModelSignal({
    id: 'ipf-ginsenoside-rb1-bleomycin-mouse-2022',
    title: 'Ginsenoside Rb1 Alleviates Bleomycin-Induced Pulmonary Inflammation and Fibrosis by Suppressing Central Nucleotide-Binding Oligomerization-, Leucine-Rich Repeat-, and Pyrin Domains-Containing Protein Three Inflammasome Activation and the NF-kappaB Pathway',
    journal: 'Drug Design, Development and Therapy',
    year: '2022',
    pmid: '35719213',
    doi: '10.2147/DDDT.S361748',
    candidate: 'Ginsenoside Rb1',
    summary: 'Ginsenoside Rb1 was tested in bleomycin-treated mice. This was not a study in people with idiopathic pulmonary fibrosis.',
    relationEvidence: 'Mice were given ginsenoside Rb1 in a bleomycin lung-fibrosis model.',
    aiIdeaPriority: 96,
  }),
  ipfModelSignal({
    id: 'ipf-melatonin-bleomycin-2023',
    title: 'Melatonin ameliorates bleomycin-induced pulmonary fibrosis via activating NRF2 and inhibiting galectin-3 expression',
    journal: 'Acta Pharmacologica Sinica',
    year: '2023',
    pmid: '36333557',
    doi: '10.1038/s41401-022-01018-x',
    candidate: 'Melatonin',
    summary: 'Melatonin was tested in a bleomycin pulmonary-fibrosis model and lung cells. This was not a study in people with idiopathic pulmonary fibrosis.',
    relationEvidence: 'The paper tested melatonin in a bleomycin pulmonary-fibrosis model.',
    aiIdeaPriority: 95,
  }),
  ipfModelSignal({
    id: 'ipf-ramelteon-bleomycin-mouse-2024',
    title: 'Preventive effects of Ramelteon on bleomycin-induced pulmonary fibrosis in mice',
    journal: 'Naunyn-Schmiedeberg\'s Archives of Pharmacology',
    year: '2024',
    pmid: '38032492',
    doi: '10.1007/s00210-023-02867-x',
    candidate: 'Ramelteon',
    summary: 'Ramelteon was tested in a bleomycin mouse model of pulmonary fibrosis. This was not a study in people with idiopathic pulmonary fibrosis.',
    relationEvidence: 'Ramelteon reduced fibrosis measures in a bleomycin mouse model in this study.',
    aiIdeaPriority: 94,
  }),
  ipfModelSignal({
    id: 'ipf-empagliflozin-bleomycin-rat-2023',
    title: 'Empagliflozin Ameliorates Bleomycin-Induced Pulmonary Fibrosis in Rats by Modulating Sesn2/AMPK/Nrf2 Signaling and Targeting Ferroptosis and Autophagy',
    journal: 'International Journal of Molecular Sciences',
    year: '2023',
    pmid: '37298433',
    doi: '10.3390/ijms24119481',
    candidate: 'Empagliflozin',
    summary: 'Empagliflozin was tested in bleomycin-treated rats. This was not a study in people with idiopathic pulmonary fibrosis.',
    relationEvidence: 'The study evaluated empagliflozin in a rat bleomycin model of pulmonary fibrosis.',
    aiIdeaPriority: 93,
  }),
  ipfModelSignal({
    id: 'ipf-berberine-bleomycin-mouse-2023',
    title: 'Berberine regulates pulmonary inflammatory microenvironment and decreases collagen deposition in response to bleomycin-induced pulmonary fibrosis in mice',
    journal: 'Basic & Clinical Pharmacology & Toxicology',
    year: '2023',
    pmid: '36433932',
    doi: '10.1111/bcpt.13818',
    candidate: 'Berberine',
    summary: 'Berberine was tested in bleomycin-treated mice. This was not a study in people with idiopathic pulmonary fibrosis.',
    relationEvidence: 'The study evaluated berberine in a mouse model of bleomycin-induced pulmonary fibrosis.',
    aiIdeaPriority: 92,
  }),
  ipfModelSignal({
    id: 'ipf-tudca-bleomycin-2021',
    title: 'Tauroursodeoxycholic acid alleviates pulmonary endoplasmic reticulum stress and epithelial-mesenchymal transition in bleomycin-induced lung fibrosis',
    journal: 'BMC Pulmonary Medicine',
    year: '2021',
    pmid: '33952237',
    doi: '10.1186/s12890-021-01514-6',
    candidate: 'Tauroursodeoxycholic acid (TUDCA)',
    summary: 'Tauroursodeoxycholic acid was tested in bleomycin lung-fibrosis research. This was not a study in people with idiopathic pulmonary fibrosis.',
    relationEvidence: 'This paper tested tauroursodeoxycholic acid in a bleomycin lung-fibrosis model.',
    aiIdeaPriority: 91,
  }),
  ipfModelSignal({
    id: 'ipf-fisetin-bleomycin-2020',
    title: 'Fisetin Alleviated Bleomycin-Induced Pulmonary Fibrosis Partly by Rescuing Alveolar Epithelial Cells From Senescence',
    journal: 'Frontiers in Pharmacology',
    year: '2020',
    pmid: '33381023',
    doi: '10.3389/fphar.2020.553690',
    candidate: 'Fisetin',
    summary: 'Fisetin was tested in a bleomycin pulmonary-fibrosis model. This was not a study in people with idiopathic pulmonary fibrosis.',
    relationEvidence: 'This paper studied fisetin in bleomycin-induced pulmonary fibrosis.',
    aiIdeaPriority: 90,
  }),
  ipfModelSignal({
    id: 'ipf-sulforaphane-bleomycin-mouse-2018',
    title: 'Sulforaphane attenuates pulmonary fibrosis by inhibiting the epithelial-mesenchymal transition',
    journal: 'BMC Pharmacology and Toxicology',
    year: '2018',
    pmid: '29609658',
    doi: '10.1186/s40360-018-0204-7',
    candidate: 'Sulforaphane',
    summary: 'Sulforaphane was tested in mice and lung cells in a pulmonary-fibrosis study. This was not a study in people with idiopathic pulmonary fibrosis.',
    relationEvidence: 'The study tested sulforaphane in mice and cells in pulmonary-fibrosis research.',
    aiIdeaPriority: 89,
  }),
]

const normalizedCondition = (value) => String(value || '')
  .toLowerCase()
  .replace(/[^a-z0-9]+/g, ' ')
  .trim()

const matchesCondition = (signal, condition) => {
  const received = normalizedCondition(condition)
  return (signal.conditionAliases || []).some((alias) => {
    const expected = normalizedCondition(alias)
    return received === expected || received.startsWith(`${expected} `)
  })
}

// Return copies because downstream source enrichment may add metadata.
export const recentResearchSignalsFor = (condition) => RECENT_RESEARCH_SIGNALS
  .filter((signal) => matchesCondition(signal, condition))
  .map((signal) => ({
    ...signal,
    supportingSourceIds: [...(signal.supportingSourceIds || [])],
    candidateLeads: (signal.candidateLeads || []).map((candidate) => ({ ...candidate })),
  }))
