// Vercel Serverless Function for the main research pipeline.
//
// Modes supported:
//   - "research"   : full evidence-based analysis of treatments for the condition,
//                    tailored to patient profile, with contraindication check
//   - "repurpose"  : EveryCure-style out-of-the-box drug repurposing analysis
//                    ("professor-to-students" reasoning)
//   - "trials"     : narrative analysis layered on top of live ClinicalTrials.gov
//                    data (the structured pull happens in /api/trials)
//   - "chat"       : free-form follow-up in the same context
//
// Audience toggle: "medical" (clinician language) or "layperson" (10th-grade).
//
// GROUNDING: for "research" and "repurpose" modes, we first call /api/evidence
// to fan out across PubMed + Europe PMC + OpenAlex + Cochrane + openFDA,
// de-duplicate by DOI/PMID, pull OA full text when available, and hand Claude
// a grounded evidence pack. Claude is instructed to cite ONLY from that pack.
// This eliminates the single biggest failure mode of consumer AI medical
// research: hallucinated citations that confidently reference papers the AI
// never actually read.
//
// All modes return Claude's text; the frontend parses structured blocks
// (PROVIDER/TREATMENT/EFFICACY/SAFETY/COST/REFERENCES) into the comparison chart.

import evidenceHandler from './evidence.js';
import validateHandler from '../lib/validate.js';
import trialsHandler from './trials.js';
import { getDossier } from '../lib/disease-dossier.js';

const MODEL = 'claude-sonnet-4-20250514';
// Vercel Hobby has a hard 60s serverless cap. Measured Claude Sonnet 4
// throughput on our grounded prompts is ~60-100 tok/s TTFT-to-stop,
// which puts 4500 max_tokens at 45-75s of pure generation — too close
// to the cap for a reliable single-shot response (we were seeing
// FUNCTION_INVOCATION_TIMEOUT every attempt after the gather phase
// completed successfully). Cutting to 2500 gives us ~25-40s generation
// which fits comfortably with the heavy grounded prompt + input
// context. 2500 tokens is still enough for a tight 8-section
// clinician-grade summary — we adjusted the prompt scaffold to match.
const MAX_TOKENS = 2500;

const invokeInProcess = async (handler, body) => {
  let captured = { status: 200, body: null };
  const res = {
    setHeader() {}, status(c) { captured.status = c; return this; },
    end() {}, json(o) { captured.body = o; return this; }
  };
  try {
    await handler({ method: 'POST', body, headers: {}, query: {} }, res);
  } catch (e) {
    captured.status = 500;
    captured.body = { error: e.message };
  }
  return captured.body;
};

const invokeEvidence = (body) => invokeInProcess(evidenceHandler, body);
const invokeValidate = (body) => invokeInProcess(validateHandler, body);
const invokeTrials = (body) => invokeInProcess(trialsHandler, body);

// Build a Claude-readable digest of the disease-intake dossier. This is the
// AI's "what do I know about this disease" context — canonical name, synonyms,
// subspecialty, the world-class centers known for this specific disease (not
// just generic famous hospitals), the landmark trial acronyms, the patient
// advocacy orgs. Without this, Claude researches IPF and Retinitis Pigmentosa
// with the same generic vocabulary; with this, it knows to talk about
// Pittsburgh Simmons + UCSF for ILD and Bascom Palmer + Wilmer for RP.
const buildDossierBlock = (dossier) => {
  if (!dossier) return '';
  const safe = (v) => (v == null ? '' : String(v));
  const lines = [];
  lines.push(`DISEASE DOSSIER (realtime intake, generated by ${safe(dossier.generatedBy) || 'AI agent'}, uncertainty ${dossier.uncertainty ?? '?'}):`);
  lines.push(`  Canonical name: ${safe(dossier.canonical)}`);
  if (dossier.subspecialty) lines.push(`  Subspecialty: ${dossier.subspecialty}`);
  if ((dossier.synonyms || []).length) {
    lines.push(`  Known synonyms / aliases: ${dossier.synonyms.join(', ')}`);
  }
  if ((dossier.meshTerms || []).length) {
    lines.push(`  NCBI MeSH terms used for PubMed fan-out: ${dossier.meshTerms.join(', ')}`);
  }
  if (dossier.icd10) lines.push(`  ICD-10: ${dossier.icd10}`);
  if ((dossier.topCenters || []).length) {
    lines.push(`  Top centers specific to this disease (dossier — you MUST surface these in the "Top Centers & Experts" section unless you have grounded evidence to override):`);
    dossier.topCenters.forEach((c) => {
      const loc = [c.city, c.country].filter(Boolean).join(', ');
      lines.push(`    - ${safe(c.name)}${loc ? ` (${loc})` : ''}${c.why ? ` — ${c.why}` : ''}`);
    });
  }
  if ((dossier.keyInvestigators || []).length) {
    lines.push(`  Key investigators (dossier):`);
    dossier.keyInvestigators.forEach((i) => {
      lines.push(`    - ${safe(i.name)}${i.affiliation ? ` (${i.affiliation})` : ''}${i.why ? ` — ${i.why}` : ''}`);
    });
  }
  if ((dossier.patientAdvocacy || []).length) {
    lines.push(`  Patient advocacy / registries (include these in the "Patient Advocacy & Resources" section):`);
    dossier.patientAdvocacy.forEach((a) => {
      lines.push(`    - ${safe(a.name)}${a.url ? ` — ${a.url}` : ''}${a.why ? ` — ${a.why}` : ''}`);
    });
  }
  if ((dossier.landmarkTrials || []).length) {
    lines.push(`  Landmark trials / acronyms:`);
    dossier.landmarkTrials.forEach((t) => {
      lines.push(`    - ${safe(t.acronym)}${t.name ? ` (${t.name})` : ''}${t.topic ? ` — ${t.topic}` : ''}`);
    });
  }
  if ((dossier.commonComorbidities || []).length) {
    lines.push(`  Common comorbidities to screen for: ${dossier.commonComorbidities.join(', ')}`);
  }
  if ((dossier.redFlags || []).length) {
    lines.push(`  Common misdiagnoses / red flags (cover these in the "Red Flags / Don't Do This" section):`);
    dossier.redFlags.forEach((r) => lines.push(`    - ${r}`));
  }
  if (dossier.notes) lines.push(`  Agent notes: ${dossier.notes}`);
  if (dossier.uncertainty != null && dossier.uncertainty >= 0.6) {
    lines.push(`  IMPORTANT: the dossier agent flagged HIGH UNCERTAINTY for this condition. Treat the dossier as a starting hypothesis, not fact. Prefer grounded evidence and explicitly disclose when you are relying on the dossier for a non-grounded claim.`);
  }
  return lines.join('\n') + '\n';
};

// Build a compact Claude-readable digest of the trials fan-out. We give
// Claude a ranked list of the TOP trials by category (recruiting, expanded
// access, OLE) so it can explicitly cover each section without blowing the
// token budget on hundreds of studies. Without this block the user gets a
// research answer that is silently blind to Expanded Access and OLE
// programs — which is exactly what they caught us missing.
const buildTrialsBlock = (trials) => {
  if (!trials) return '';
  const studies = Array.isArray(trials.studies) ? trials.studies : [];
  if (!studies.length) return '';

  const fmt = (s) => {
    const phase = (s.phases || []).join('/') || 'N/A';
    const loc = (s.contacts?.locations || []).slice(0, 2)
      .map((l) => [l.facility, l.city, l.country].filter(Boolean).join(', '))
      .join(' | ') || 'no sites listed';
    const centers = (s.topCenters || []).slice(0, 3).join('; ');
    const designations = [];
    if (s.designations?.fastTrack) designations.push('fast-track');
    if (s.designations?.breakthrough) designations.push('breakthrough');
    if (s.designations?.orphan) designations.push('orphan');
    if (s.designations?.hasExpandedAccess) designations.push('EXPANDED-ACCESS');
    if (s.designations?.hasOpenLabelExtension) designations.push('OPEN-LABEL-EXTENSION');
    if (s.designations?.hasPostTrialAccess) designations.push('post-trial-access');
    if (s.designations?.hasPayToAccess) designations.push('PAY-TO-ACCESS');
    return `  - ${s.nctId} · ${phase} · ${s.status} · ${s.briefTitle || '(untitled)'}
    Sponsor: ${s.sponsor || 'unknown'}${centers ? ` · Top centers: ${centers}` : ''}
    Sites: ${loc}${designations.length ? ` · Flags: ${designations.join(', ')}` : ''}
    Interventions: ${(s.interventions || []).slice(0, 3).map((i) => i.name).join(' | ') || '(none listed)'}
    URL: ${s.url}`;
  };

  // Same budget story as the grounding block: bigger trial lists chew
  // input tokens AND output tokens (Claude tries to discuss each).
  // 8 + 4 + 4 + 4 is enough to surface the most important programs
  // while staying under Vercel's 60s synth cap.
  const recruiting = studies.filter((s) => s.acceptingNewPatients && !s.isExpandedAccessStudy && !s.designations?.hasOpenLabelExtension).slice(0, 8);
  const ea = studies.filter((s) => s.designations?.hasExpandedAccess).slice(0, 4);
  const ole = studies.filter((s) => s.designations?.hasOpenLabelExtension).slice(0, 4);
  const topCenter = studies.filter((s) => s.hasTopCenter).slice(0, 4);

  const chunks = [];
  chunks.push(`LIVE CLINICAL TRIALS PULL (ClinicalTrials.gov, fanned across condition + synonyms + expanded-access studyType + OLE title search):
Breakdown: ${trials.breakdown ? JSON.stringify(trials.breakdown) : '(unknown)'}
Synonyms used: ${(trials.dossier?.synonyms || []).join(', ') || '(single term)'}
MeSH terms used: ${(trials.dossier?.meshTerms || []).join(', ') || '(none)'}`);

  if (recruiting.length) {
    chunks.push(`\nRECRUITING TRIALS (top ${recruiting.length} by promise score):\n${recruiting.map(fmt).join('\n\n')}`);
  }
  if (ea.length) {
    chunks.push(`\nEXPANDED ACCESS / COMPASSIONATE USE (${ea.length} record(s) — patients who don't qualify for a trial may still be able to get the drug this way):\n${ea.map(fmt).join('\n\n')}`);
  } else {
    chunks.push(`\nEXPANDED ACCESS / COMPASSIONATE USE: none surfaced by CT.gov studyType=EXPANDED_ACCESS query. DO NOT invent programs. If you know of a well-publicised compassionate use program that isn't on CT.gov (e.g. a company-run charitable access pathway), name it with a direct-to-sponsor URL and explicitly flag it as "not listed on CT.gov — verify with the sponsor."`);
  }
  if (ole.length) {
    chunks.push(`\nOPEN-LABEL EXTENSION STUDIES (${ole.length} record(s) — for patients already in a prior trial):\n${ole.map(fmt).join('\n\n')}`);
  } else {
    chunks.push(`\nOPEN-LABEL EXTENSION STUDIES: none surfaced. Still mention in the answer that patients currently in Phase 2/3 trials should ask their PI whether an OLE is planned — most multi-year programs have one even before it lists on CT.gov.`);
  }
  if (topCenter.length) {
    chunks.push(`\nTRIALS AT TOP CENTERS (${topCenter.length}):\n${topCenter.map(fmt).join('\n\n')}`);
  }

  return chunks.join('\n') + '\n';
};

const buildGroundingBlock = (evidence) => {
  if (!evidence) return '';
  // Top-12 rather than top-25. Each item costs ~200-400 input tokens
  // (title + authors + journal + year + excerpt + quality flags). 25
  // items was ~6-9k input tokens just on the grounding block, which
  // slowed TTFT measurably AND pushed total generation past the 60s
  // Vercel cap. 12 items × the best-scored sources is still enough for
  // a well-grounded 8-section synthesis and keeps the prompt lean.
  const items = (evidence.groundedForPrompt || []).slice(0, 12);
  if (!items.length) return '';
  const packed = items.map((it, i) => {
    const tierLabel = it.tier ? ` [TIER ${it.tier}]` : '';
    const oa = it.openAccess ? ' [OPEN ACCESS]' : '';
    // Access level is the single most important disclosure — Claude must
    // never claim details from a paper beyond what is visible in the excerpt.
    const access =
      it.accessLevel === 'full-text' ? ' [FULL-TEXT]'
      : it.accessLevel === 'abstract' ? ' [ABSTRACT-ONLY]'
      : ' [METADATA-ONLY]';
    // Curated KB items are hand-picked landmark references for this disease
    // (guidelines, defining RCTs, FDA labels). Tag them distinctly so Claude
    // knows these are the canonical ground-truth floor.
    const kbTag = it.isCuratedKB
      ? ` [CURATED KB${it.kbCategory ? ` · ${it.kbCategory.toUpperCase()}` : ''}]`
      : '';
    // Quality signals — render the two most important positive and negative
    // flags inline so Claude weights the source appropriately when citing.
    const qualityTags = [];
    if (it.isMetaAnalysis) qualityTags.push('META-ANALYSIS');
    else if (it.isSystematicReview) qualityTags.push('SYSTEMATIC-REVIEW');
    else if (it.isRCT) qualityTags.push('RCT');
    if (it.isPreprint) qualityTags.push('PREPRINT-NOT-PEER-REVIEWED');
    // Country-of-research flag — rendered only when penalised. The country
    // code is the first author's institutional country. This reflects a
    // documented integrity-concern weighting, not a blanket dismissal.
    const penalisedCountries = { CN: 'CHINA', RU: 'RUSSIA', IR: 'IRAN', PK: 'PAKISTAN', IN: 'INDIA', VN: 'VIETNAM' };
    if (it.firstAuthorCountry && penalisedCountries[it.firstAuthorCountry]) {
      qualityTags.push(`FIRST-AUTHOR-${penalisedCountries[it.firstAuthorCountry]}-INTEGRITY-CONCERN`);
    }
    const qTag = qualityTags.length ? ` [${qualityTags.join(' · ')}]` : '';
    const src = (it.sources || []).join('+');
    const pubLine = it.publisher ? ` · Publisher: ${it.publisher}` : '';
    const countryLine = it.firstAuthorCountry ? ` · 1st-author country: ${it.firstAuthorCountry}` : '';
    return `[#${i + 1}]${kbTag}${tierLabel}${access}${oa}${qTag} ${it.title || '(no title)'}
      Journal: ${it.journal || '?'}${pubLine} · Year: ${it.year || '?'} · Sources: ${src} · Citations: ${it.citations || 0}${countryLine}
      URL: ${it.url || '(no URL)'}
      Content: ${(it.text || '').slice(0, 3000) || '(no text available — metadata only; you may name this paper but MUST NOT claim anything about its results, methods, or conclusions)'}`;
  }).join('\n\n');

  const fdaBits = [];
  (evidence.fdaLabels || []).forEach((f) => {
    if (!f.label) return;
    fdaBits.push(
      `FDA LABEL · ${f.drug || (f.label.genericName || []).join(', ')}
      Indications: ${(f.label.indications || '').slice(0, 900)}
      Warnings: ${(f.label.warnings || '').slice(0, 900)}
      Contraindications: ${(f.label.contraindications || '').slice(0, 600)}
      Drug interactions: ${(f.label.drugInteractions || '').slice(0, 900)}
      Top FAERS reactions: ${(f.topAdverseEvents || []).map((e) => `${e.reaction} (${e.reports})`).join(', ')}
      Source: ${f.label.url}`
    );
  });
  (evidence.fdaManufacturers || []).forEach((m) => {
    if (!m.enforcementActions?.length) return;
    fdaBits.push(
      `FDA ENFORCEMENT · manufacturer ${m.manufacturer}
      Actions: ${m.enforcementActions.slice(0, 6).map((a) => `${a.recallInitiationDate} Class ${a.classification}: ${a.reason}`).join(' | ')}`
    );
  });

  // Curated knowledge base context block — canonical facts, lifestyle, and
  // red-flag contraindications for this disease, from the hand-curated KB.
  const kb = evidence.knowledgeBase;
  let kbBlock = '';
  if (kb && kb.matched) {
    const facts = (kb.canonicalFacts || []).slice(0, 15);
    const lifestyle = (kb.lifestyleRecommendations || []).slice(0, 10);
    const redFlags = (kb.redFlags || []).slice(0, 10);
    kbBlock = `CURATED KNOWLEDGE BASE — ${kb.condition} (v${kb.version || '?'}, ${kb.itemCount} pinned references)
The evidence items tagged [CURATED KB] below are hand-picked landmark references for this specific disease. They are the canonical ground-truth floor; every query on this condition always sees them. Live-fetched items ([PubMed], [EuropePMC], etc.) supplement them.

CANONICAL FACTS (hand-reviewed, each backed by at least one KB item):
${facts.map((f, i) => `  - ${f.claim}  [refs: ${(f.evidenceRefs || []).join(', ')}]`).join('\n') || '  (none)'}

LIFESTYLE / NON-DRUG GUIDANCE:
${lifestyle.map((l) => `  - ${l.recommendation}`).join('\n') || '  (none)'}

ABSOLUTE RED FLAGS (these are established contraindications — do not recommend them):
${redFlags.map((r) => `  - ${r}`).join('\n') || '  (none)'}

Use these canonical facts and red flags as your backbone. Live evidence supplements them. If a live item contradicts a canonical fact, say so explicitly and weigh the quality of each.
`;
  }

  // Quality-exclusion summary — tell Claude what we already filtered OUT so
  // it doesn't cite papers we pulled out of the pool and doesn't try to
  // compensate by naming known-retracted titles from general knowledge.
  const qb = evidence.qualityBreakdown;
  let qualityNoteBlock = '';
  if (qb) {
    const bits = [];
    if (qb.retractedExcluded > 0) {
      bits.push(`${qb.retractedExcluded} retracted paper(s) were FOUND in the initial pool and EXCLUDED from this pack. Do not cite these titles from memory: ${qb.retractedTitles.map((r) => `"${(r.title || '').slice(0, 80)}"`).join('; ')}.`);
    }
    if (qb.predatoryExcluded > 0) {
      bits.push(`${qb.predatoryExcluded} paper(s) from documented predatory publishers were EXCLUDED.`);
    }
    if (qb.preprintsInPool > 0) {
      bits.push(`${qb.preprintsInPool} preprint(s) are still present but tagged — flag them to the user as "preprint, not peer-reviewed".`);
    }
    if (qb.countryConcernInPromptPack > 0) {
      bits.push(`${qb.countryConcernInPromptPack} of the items below have a first author from a jurisdiction with documented systemic research-integrity concerns (CN, RU, IR, PK, IN, VN). They carry a "FIRST-AUTHOR-*-INTEGRITY-CONCERN" tag. You may still cite them, but: (a) prefer equivalent Western-origin evidence when available, (b) when you do cite them, explicitly note the origin in the text of your answer, and (c) never cite them as the SOLE evidence for a safety-critical claim.`);
    }
    if (bits.length) qualityNoteBlock = `SOURCE-QUALITY NOTES FOR THIS PACK:\n${bits.map((b) => `- ${b}`).join('\n')}\n\n`;
  }

  return `GROUNDED EVIDENCE PACK — you MUST cite only from this list. If a claim is not supported by one of these items, say "No grounded evidence in pack" instead of making one up.

${kbBlock}

${qualityNoteBlock}CITATION ACCESS RULES (strict — many medical journals are paywalled and we deliberately only pull what is legal to share):
- Each item is tagged [FULL-TEXT], [ABSTRACT-ONLY], or [METADATA-ONLY] to tell you exactly how much of it you have read.
- Items also tagged [CURATED KB] are hand-curated landmark references — prefer them when the topic is directly covered.
- [FULL-TEXT] items: you may cite methods, results, secondary endpoints, subgroups, adverse events, and figures, because you actually have the body text.
- [ABSTRACT-ONLY] items: you may ONLY cite things that literally appear in the Content field (which is the peer-reviewed abstract or, for KB items, editor summary + verbatim passages). You may NOT claim anything about sub-group analyses, exact adverse-event frequencies beyond what the abstract states, study methods beyond what the abstract states, or any detail that requires having read the full paper.
- [METADATA-ONLY] items: you may NAME the paper and reference it as "peer-reviewed source exists (abstract/full text unavailable in this pack)" but you may NOT claim anything about its findings.
- In EVERY citation you write, append the access tag in brackets after the URL, exactly like this: \`[#3] (NEJM 2014) https://... [ABSTRACT-ONLY] — "quoted passage"\`. This is non-negotiable.
- When the Content shows an "Editor's summary", treat that as context — do not quote it as if it were from the paper. Quote only "Verbatim passage" blocks verbatim, or abstract text for live items.
- When you quote, copy the text verbatim from the Content field below and include the URL.

SOURCE-QUALITY PRIORITY ORDER (use this when two items conflict):
  1. [CURATED KB] items (hand-curated landmark refs for this disease)
  2. Cochrane Systematic Reviews + [META-ANALYSIS]
  3. [SYSTEMATIC-REVIEW] + [RCT] in A+ / A tier journals
  4. Observational / cohort studies in A+ / A tier journals
  5. [RCT] / [META-ANALYSIS] in B tier journals
  6. Anything else peer-reviewed
  7. [PREPRINT-NOT-PEER-REVIEWED] items (only cite as supplementary, flag explicitly)
  Items carrying FIRST-AUTHOR-*-INTEGRITY-CONCERN drop one tier in this order.

${packed}

${fdaBits.join('\n\n')}`;
};

const buildPatientContext = (p = {}) => {
  const lines = [];
  if (p.condition) lines.push(`PRIMARY CONDITION TO RESEARCH: ${p.condition}${p.stage ? ` (stage: ${p.stage})` : ''}`);
  if (p.age) lines.push(`Age: ${p.age}`);
  if (p.gender) lines.push(`Gender: ${p.gender}`);
  if (p.weight) lines.push(`Weight: ${p.weight}`);
  if (p.smoking) lines.push(`Smoking history: ${p.smoking}`);
  if (p.exercise) lines.push(`Exercise / activity: ${p.exercise}`);
  if (p.diagnoses) lines.push(`ALL current diagnoses (do NOT research these unless relevant for interactions): ${p.diagnoses}`);
  if (p.medications) lines.push(`Current medications (check every recommendation for interaction/contraindication): ${p.medications}`);
  if (p.symptoms) lines.push(`Current symptoms: ${p.symptoms}`);
  if (p.labWork) lines.push(`Lab work / pulmonary function / other studies: ${p.labWork}`);
  if (p.scans) lines.push(`Recent imaging / scans: ${p.scans}`);
  return lines.length ? lines.join('\n') : 'No patient context provided.';
};

const audienceLine = (audience) =>
  audience === 'medical'
    ? 'AUDIENCE: Medical professional. Use precise clinical terminology, include pharmacology, dosing, and mechanism where relevant.'
    : 'AUDIENCE: Non-medical reader (high-school / 10th-grade education). Explain every medical term in plain language. Keep sentences short.';

const SHARED_GUARDRAILS = `
CITATION RULES (absolute — the single biggest failure mode of AI in medical research is hallucinated citations):
- CITE ONLY FROM THE GROUNDED EVIDENCE PACK provided below. Do not invent, paraphrase-without-URL, or cite from general knowledge.
- Every factual claim about efficacy, safety, interactions, or outcomes MUST reference at least one evidence-pack item by its number (e.g. "[#3]") and include a verbatim quoted passage from that item's Content and the exact URL.
- If the evidence pack does not support a claim, write "No grounded evidence in pack" — DO NOT make one up.
- Prefer A+ and A tier journals (NEJM, Lancet, JAMA, BMJ, Nature Medicine, Cochrane, ERJ, AJRCCM, Thorax, Chest) over B/C.
- Weight evidence: US/Western Europe = full; other developed = moderate; China = low (flag explicitly). Mexico/Vietnam/India stem-cell sources should be flagged.

ACCESS-LEVEL HONESTY (critical — many high-impact medical journals are paywalled):
- Every evidence item has an [ACCESS] tag: [FULL-TEXT], [ABSTRACT-ONLY], or [METADATA-ONLY].
- You MUST include this tag after every URL you cite.
- For [ABSTRACT-ONLY] papers: you have the peer-reviewed abstract and nothing else. You may cite what the abstract literally says. You may NOT invent numeric values, methodological details, subgroup outcomes, or adverse-event frequencies that are not in the abstract text.
- For [METADATA-ONLY] papers: you may name the paper but you must NOT claim what it found. Say "a peer-reviewed paper exists but the abstract/full text were not available to me in this pack."
- If a claim cannot be supported without overreaching past abstract content, state the limitation explicitly: "Based on the abstract; the full methods/results were not accessible."

PATIENT-SPECIFIC SAFETY (critical):
- Before recommending any drug, check the patient's current medication list for interactions and contraindications. Name the specific interaction and severity.
- Consider age, comorbidities, labs/PFTs, and scans when assessing suitability.
- Flag treatments that are contraindicated for this specific patient even if they are effective in the general population.

GEOGRAPHIC / SOURCING RULES:
- For stem cell therapies, clinics in China, Vietnam, Mexico, or India must be excluded unless explicitly requested. Prefer US/Western Europe clinics whose source lab has no active FDA warning letter.
- For each stem cell treatment, state: cell type (e.g. cord blood MSCs, exosomes from MSCs, autologous adipose), source lab, delivery route (IV, nebulized/inhaled, intratracheal, intrathecal, local), dose, and whether any peer-reviewed data supports the specific product.
- Do not rely on a clinic's own advertising or press releases.

DISCLAIMERS:
- This is decision-support research, not medical advice. Final choices require a licensed physician.
`;

// Formatting rules that apply to EVERY section. Pulled out so the user's
// explicit complaint ("all the unecessary **** ****, make it bold or
// underlines things or bullet them") has a single, enforced source of truth.
const FORMATTING_RULES = `
OUTPUT FORMATTING RULES (enforce strictly — the user has explicitly complained about wall-of-text):
- Use MARKDOWN with headings (##, ###), bullets, and **bold** for key terms.
- **Bold every** drug name, trial acronym, NCT ID, percentage, dose, phone number, physician name, and center name.
- NO paragraphs longer than 3 lines. Break them into bullets.
- When comparing ≥3 items, USE A MARKDOWN TABLE, not prose.
- No filler words ("Furthermore", "Additionally", "It is worth noting that", "In conclusion"). Every sentence either gives a fact, a number, a name, or an action the patient can take.
- Every URL MUST be a real clickable markdown link: [clinicaltrials.gov/NCT01234567](https://clinicaltrials.gov/study/NCT01234567).
- For every card (treatment / trial / candidate), use the exact fixed-field structure. Do not add prose between fields.
`;

const RESEARCH_PROMPT = (patient, audience) => `You are a comprehensive medical research assistant. Produce a SCANNABLE, evidence-based analysis of treatment options for the patient's primary condition, personalised to the patient profile.

${audienceLine(audience)}

PATIENT PROFILE:
${buildPatientContext(patient)}

LENGTH BUDGET (HARD RULE — we run on a 60-second serverless slot, so you MUST fit in ~2,000 words total):
- Aim for ~125-150 words per section. Dense bullets, not paragraphs.
- Inapplicable sections: write the heading + "N/A for this condition — <one-line reason>" and move on. Do NOT pad.
- Finish all sections. Truncating mid-section is a failure; cut words elsewhere first.

Your output MUST include ALL of the following sections IN THIS ORDER. Missing a section is a failure.

## 1. Condition Snapshot
- One-sentence definition.
- Prevalence / incidence (from evidence pack or dossier).
- Typical trajectory if untreated.
- Primary medical specialty to see (from dossier).
- Disease-dossier uncertainty score if > 0.5 (be transparent about AI confidence).

## 2. Top Centers & Experts Worldwide
**Use the disease dossier's topCenters and keyInvestigators as your starting list.** Add to or correct them with grounded evidence. Present as a markdown table:

| Center | City | Phone / URL | Why it leads |
|---|---|---|---|

Then list 3–6 individual **named experts** with affiliations.
Do NOT lead with clinic self-advertising. Peer-recognised only.

## 3. Approved Treatments (Standard of Care)
Ranked by evidence strength, best first. For EACH treatment output this EXACT card structure (the UI parses these fields):

PROVIDER: <specific doctor / clinic / manufacturer with phone or URL>
TREATMENT: <drug / biologic / device / surgery; include dose, strength, route>
FDA_STATUS: <approved | off-label | investigational | expanded access | compassionate use | not FDA regulated>
LENGTH_FREQUENCY: <duration + frequency>
EFFICACY: <1-100>% — <one-line justification with grounded citation>
SAFETY: <1-100>% — <higher = safer, one-line justification>
RISKS: <serious AEs, contraindications, THIS patient's risk given meds/comorbidities>
INTERACTIONS: <named interactions vs this patient's meds, or "None identified">
COST: <USD range, note US insurance coverage>
REFERENCES: <semicolon-separated URLs from the evidence pack, each with [ACCESS] tag and quoted passage>

## 4. Recruiting Clinical Trials (Top 5–8)
Pull directly from the LIVE CLINICAL TRIALS PULL block below. Use a markdown table:

| **NCT ID** | Phase | Trial Title | Top Center? | Accepting? | Placebo? | URL |
|---|---|---|---|---|---|---|

Follow with a one-line "fit for this patient" note per trial.

## 5. Open-Label Extension (OLE) Studies
**This is a mandatory section.** These are the trials that let patients who were already in a prior study keep getting the drug. Often the ONLY way to get access to an experimental therapy long-term.

For each OLE trial (from the LIVE TRIALS PULL, section flagged "OPEN-LABEL EXTENSION STUDIES"), list NCT, parent trial, sponsor, site count, and the closest open site.

If the trials pull returned NO open-label extensions, say so explicitly AND tell the user: "Patients currently in any Phase 2/3 for this condition should ask their investigator whether an OLE is planned — most sponsors build one even before it lists on CT.gov."

## 6. Expanded Access / Compassionate Use Programs
**This is a mandatory section.** FDA's pathway for patients who don't qualify for trials to get experimental drugs. For each expanded-access record from the trials pull:

- **Program name + NCT** (if CT.gov listed) OR **Sponsor direct-to-patient URL**
- Which patients qualify (eligibility summary)
- How to apply (usually: treating physician contacts sponsor; sponsor files IND-EA with FDA)
- Cost to the patient (many are free; some sponsors charge for drug cost only)

If none surfaced on CT.gov, check the dossier's landmarkTrials + your own grounded knowledge for any **industry-sponsored expanded-access program** (e.g. Ocugen's OCU400 for RP, lecanemab EAP for early AD). Name them with the sponsor-side URL and flag "not listed on CT.gov — verify directly with sponsor."

## 7. Pay-to-Access / Charitable Access Programs
**This is a mandatory section.** Some sponsors run paid post-trial access programs (e.g. the $40,000 tier some companies charge to keep receiving a Phase 3 drug between approval and market launch). List any the patient should know about.

If you don't know of any, say so — do NOT invent programs.

## 8. Drug Repurposing Candidates (mention, don't replace the Repurpose tab)
2–4 existing drugs/supplements with plausible mechanistic rationale for this condition (brief — point the user at the dedicated Drug Repurposing tab for the full analysis).

## 9. Non-Drug / Lifestyle
Practical bullets. Tailor to the actual condition — use the dossier's lifestyleCategories as a starting checklist. For IPF that's GERD, feather pillows, pulmonary rehab, vaccinations, O₂. For RP it's UV protection, vitamin A caveats (pregnancy / liver), dietary omega-3 with warnings.

## 10. Stem Cell Therapy Landscape *(if applicable)*
Reputable US / W. Europe labs only. For each: cell type, source lab, delivery route, **FDA warning-letter status**. Exclude China / Vietnam / Mexico / India clinics by default.

## 11. Gene Therapy Landscape *(if applicable)*
Approved? In trial? Theoretical? Name specific NCT IDs and sponsors. Distinguish "cure" vs "slow progression".

## 12. Drug-Drug Interaction Check for THIS Patient
Walk through the patient's current medications one by one. For each, list every clinically meaningful interaction with the Section-3 recommendations.

## 13. What's in the Pipeline
2–5 early-phase (Phase 1/2) programs worth watching, with NCT IDs and timeline-to-possible-approval estimates.

## 14. Patient Advocacy & Resources
From the dossier's patientAdvocacy list — orgs, registries, patient foundations. Link the homepage URL for each.

## 15. Insurance & Cost Snapshot
What US commercial / Medicare typically covers. Rough out-of-pocket. Red-flag overseas clinics with undisclosed pricing.

## 16. Red Flags — DO NOT DO THIS
From the dossier's redFlags + your grounded-evidence knowledge. Concrete "don't" bullets (e.g. for IPF: "Do NOT use prednisone+azathioprine+NAC — increased mortality per PANTHER-IPF"; for LADA: "Do NOT treat as T2D with sulfonylurea — accelerates beta-cell failure").

${FORMATTING_RULES}

${SHARED_GUARDRAILS}`;

const REPURPOSE_PROMPT = (patient, audience) => `You are a medical research professor leading a graduate seminar. Your students are looking at an existing drug library and asking, for a specific patient condition, "Which already-approved medications or widely-available supplements might logically help this condition — even though no formal guideline endorses them yet?"

This is the EveryCure / drug-repurposing methodology. Think outside the box. Reason from first principles about:
- the pathophysiology of the primary condition
- known mechanisms of action of existing drugs
- shared molecular pathways with other conditions where a drug is already effective
- supportive (not definitive) peer-reviewed evidence

${audienceLine(audience)}

PATIENT PROFILE:
${buildPatientContext(patient)}

Produce a ranked list of 6-12 candidate repurposed drugs or supplements. For EACH candidate output this exact block (the UI parses it):

CANDIDATE: <name>
CLASS: <drug class or supplement category>
APPROVED_FOR: <current FDA-approved or common use>
MECHANISM_TARGET: <the specific molecular target, pathway, or biological mechanism relevant to the condition (e.g. "TGF-β signalling", "AMPK activation / autophagy", "vitamin D receptor → anti-fibrotic gene expression")>
REPURPOSE_RATIONALE: <the mechanistic logic — why would this help the primary condition? Explain the biology step-by-step, at the specified audience level.>
EVIDENCE_STRENGTH: <one of: MECHANISTIC_ONLY | PRECLINICAL | CASE_REPORT | OBSERVATIONAL | SMALL_RCT | LARGE_RCT>
SUPPORTING_EVIDENCE: <peer-reviewed support: animal studies, case reports, observational, off-label use. List URLs from the evidence pack with verbatim quoted passages. If no grounded evidence exists in the pack, say "Mechanistic hypothesis only — no human data yet".>
EFFICACY_HYPOTHESIS: <1-100>% — <one-line justification>
SAFETY: <1-100>% — <higher = safer; reference FDA label / FAERS reactions if available>
CONFIDENCE: <1-100>% — <overall confidence that this is worth physician discussion>
PATIENT_SPECIFIC_RISKS: <interactions with THIS patient's meds, age, comorbidities>
HOW_TO_DISCUSS_WITH_DOCTOR: <practical script / questions the patient should ask a physician>

After the candidate list, include:

## Reasoning Summary
Explain the top 3 candidates in plain language.

## What This Is NOT
Clearly say this is hypothesis-generation, not a prescription, and must be discussed with a physician before any change.

${SHARED_GUARDRAILS}`;

const TRIALS_PROMPT = (patient, audience, trialsData) => `You are a clinical trials analyst. You have been given a live pull of recruiting (or nearly-recruiting) trials from ClinicalTrials.gov for this patient's condition. Produce a narrative analysis that:

${audienceLine(audience)}

PATIENT PROFILE:
${buildPatientContext(patient)}

LIVE TRIAL DATA (JSON):
${JSON.stringify(trialsData, null, 2).slice(0, 120000)}

Your job:
1. Rank the most promising 5-10 trials for THIS patient based on eligibility, phase, placebo exposure, oversight (IRB, DSMB, FDA-regulated), country, and fit with their comorbidities.
2. For each, flag: accepting new patients (yes/no), placebo vs all-get-drug, fast-track / breakthrough / orphan designations, Post-Trial Access / Expanded Access / Compassionate Use / Open-Label Extension availability, location, contact info, and the direct clinicaltrials.gov URL.
3. Explicitly note any trial that is NOT a treatment study (observational, biomarker, registry) — the patient wants treatment only.
4. For each recommended trial, name the most likely interactions/contraindications vs this patient's current medications.
5. End with a plain-language "What this means for you" paragraph.

Use this structured block for each ranked trial so the UI can parse it:

TRIAL: <brief title>
NCT: <NCT ID>
URL: <https://clinicaltrials.gov/study/NCTxxxxxxxx>
PHASE: <phase(s)>
STATUS: <recruiting status>
ACCEPTING: <yes / no>
PLACEBO: <yes / no / partial>
TREATMENT_ONLY: <yes / no>
COUNTRY: <country list>
OVERSIGHT: <IRB yes/no, DSMB yes/no, FDA-regulated yes/no>
DESIGNATIONS: <fast-track / breakthrough / orphan / expanded-access / PTA / OLE flags>
FIT_FOR_PATIENT: <1-100>% — <why>
HARM_RISK: <1-100>% — <higher = safer>
INTERACTIONS: <named interactions with this patient's meds>
LOCATION_CONTACT: <closest site + contact info from data>
SUMMARY: <2-3 sentence plain-language summary>

${SHARED_GUARDRAILS}`;

export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Credentials', true);
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET,OPTIONS,PATCH,DELETE,POST,PUT');
  res.setHeader(
    'Access-Control-Allow-Headers',
    'X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version'
  );

  if (req.method === 'OPTIONS') {
    res.status(200).end();
    return;
  }

  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    const {
      mode = 'research',
      patient = {},
      audience = 'layperson',
      userQuery = '',
      chatHistory = [],
      trialsData = null,
      // Two-phase pipeline to stay under Vercel's 60s serverless cap.
      //   phase='gather'     — fan out to dossier+evidence+trials, return
      //                         those pools to the client, DON'T call Claude.
      //   phase='synthesize' — skip fan-out, use dossier+evidence+trials
      //                         provided by the client, run Claude only.
      //   phase='all' (default for backward compat & chat/trials/repurpose modes):
      //                         do everything in one request. Research mode
      //                         from the UI now uses gather→synthesize; the
      //                         single-shot path is still there for the API.
      phase = 'all',
      providedDossier = null,
      providedEvidence = null,
      providedTrials = null
    } = req.body || {};

    const apiKey = process.env.ANTHROPIC_API_KEY;
    if (!apiKey) {
      return res.status(500).json({
        error: 'Server configuration error: ANTHROPIC_API_KEY not set.'
      });
    }

    // Effective condition — prefer patient.condition, but fall back to the
    // user's latest message (chat input) if the profile field is empty. This
    // is the fix for the "I type RP in the chat, AI refuses because no
    // condition set" UX bug. The dossier agent itself vets whatever we
    // pass; a junk string returns a high-uncertainty fallback.
    const latestUserMsg = (() => {
      if (userQuery && String(userQuery).trim()) return String(userQuery).trim();
      const lastUser = [...(chatHistory || [])].reverse().find((m) => m?.role === 'user');
      return lastUser?.content ? String(lastUser.content).trim() : '';
    })();
    // Heuristic: trim long conversational messages down to the medical noun
    // phrase. "Ok RP, give me info" → "RP". If the message is short (< 60
    // chars), just pass it whole to the dossier agent (it handles aliases).
    const extractConditionFromMessage = (msg) => {
      if (!msg) return '';
      const clean = msg.replace(/["?.,!]+/g, ' ').trim();
      if (clean.length < 60) return clean;
      const m = clean.match(/\b([A-Z]{2,6}|[a-z][a-z\- ]{3,40})\b/);
      return (m && m[1]) ? m[1] : clean.slice(0, 60);
    };
    const effectiveCondition =
      (patient.condition || '').trim() ||
      extractConditionFromMessage(latestUserMsg);

    // Research pipeline — three phases:
    //   (1) Disease-intake agent (Haiku, 24h cache) — builds structured
    //       dossier for ANY condition, including aliases like "RP" or
    //       "LADA". Runs for ALL modes now, even chat, so the agent has
    //       disease context from the very first turn.
    //   (2) Evidence + Trials in parallel, sharing the one dossier call.
    //   (3) Claude Sonnet synthesis with the dossier injected as context.
    let evidence = null;
    let trials = null;
    let dossier = null;

    // Phase: 'synthesize' trusts client-provided pools, skips fan-out.
    // Everything else (gather / all) does the live pulls.
    if (phase === 'synthesize') {
      dossier = providedDossier || null;
      evidence = providedEvidence || null;
      trials = providedTrials || null;
    } else {
      if (effectiveCondition) {
        dossier = await getDossier(effectiveCondition);
      }

      if (mode === 'research' || mode === 'repurpose') {
        const drugs = (patient.medications || '')
          .split(/[,;\n]/).map((s) => s.trim().split(/\s+/)[0]).filter(Boolean).slice(0, 6);

        // Budgets tuned for the 60s Vercel cap. `limitPerSource` used to be 5
        // and trials `pageSize` 60 — that produced >80 evidence items and >200
        // trial blobs which the grounding formatter had to serialise into the
        // Claude prompt, and every extra item chews a few extra ms on the
        // wire and a few more tokens on Claude's generation. 3 + 30 gives us
        // still-dense coverage (the dossier + KB fill in the gaps) while
        // letting the whole pipeline finish under the deadline.
        const [evidenceResult, trialsResult] = await Promise.all([
          invokeEvidence({
            condition: effectiveCondition,
            treatments: ['treatment', 'clinical trial', 'systematic review', 'meta-analysis'],
            drugs,
            manufacturers: [],
            limitPerSource: 3,
            includeFullText: true,
            dossier
          }),
          invokeTrials({
            condition: effectiveCondition,
            recruitingOnly: false,
            treatmentOnly: true,
            pageSize: 30,
            dossier
          })
        ]);
        evidence = evidenceResult;
        trials = trialsResult;
      }
    }

    // Phase='gather' short-circuits here. We hand the raw pools back to the
    // client, which will then call us again with phase='synthesize' and the
    // pools attached. This splits the >60s single-shot pipeline into two
    // sub-60s serverless invocations.
    if (phase === 'gather') {
      return res.status(200).json({
        phase: 'gather',
        dossier,
        evidence,
        trials
      });
    }
    const groundingBlock = evidence ? buildGroundingBlock(evidence) : '';
    const trialsBlock = trials ? buildTrialsBlock(trials) : '';
    const dossierBlock = dossier ? buildDossierBlock(dossier) : '';

    // Extra context layers stitched onto the base mode prompt. Order matters:
    // dossier first (the AI's starting hypothesis about the disease), then
    // grounded evidence pack (what the literature actually says), then the
    // live trials pull (what's currently enrolling / offering expanded
    // access). Later blocks override earlier ones — that's intentional.
    const extraContext = [dossierBlock, groundingBlock, trialsBlock]
      .filter(Boolean)
      .join('\n\n');

    let systemPrompt;
    switch (mode) {
      case 'repurpose':
        systemPrompt = REPURPOSE_PROMPT(patient, audience) +
          (extraContext ? `\n\n${extraContext}` : '');
        break;
      case 'trials':
        systemPrompt = TRIALS_PROMPT(patient, audience, trialsData || {});
        break;
      case 'chat': {
        // Chat mode supports TWO scenarios:
        //   (a) Follow-up after a prior Research / Repurpose / Trials run,
        //       where the client sent the prior analyses + cached evidence
        //       pack so Claude can answer "why did you rate X over Y".
        //   (b) Cold-start: user types a disease directly into the chat bar
        //       with no profile filled in and no prior analyses. The agent
        //       must STILL answer substantively — that was the whole point
        //       of the user's complaint ("don't refuse, answer the
        //       question"). In this case we use the dossier we just built
        //       from their message as the disease context.
        const priorPieces = [];
        const prior = req.body?.priorAnalyses || {};
        if (prior.research)  priorPieces.push(`=== PRIOR "RESEARCH" ANALYSIS (produced earlier in this session) ===\n${String(prior.research).slice(0, 25000)}`);
        if (prior.repurpose) priorPieces.push(`=== PRIOR "REPURPOSE" ANALYSIS ===\n${String(prior.repurpose).slice(0, 20000)}`);
        if (prior.trials)    priorPieces.push(`=== PRIOR "TRIALS" ANALYSIS ===\n${String(prior.trials).slice(0, 20000)}`);
        const hasPriors = priorPieces.length > 0;

        const cachedPack = Array.isArray(req.body?.evidencePack) ? req.body.evidencePack.slice(0, 18) : [];
        const chatGrounding = cachedPack.length
          ? buildGroundingBlock({ groundedForPrompt: cachedPack, fdaLabels: [], fdaManufacturers: [] })
          : '';

        // If we got a usable dossier (patient.condition OR extracted from the
        // user's message), include it so Claude knows what disease we're
        // talking about even without a profile or prior analysis.
        const dossierInChat = dossier && dossier.canonical ? buildDossierBlock(dossier) : '';

        // Effective-condition context — even if the dossier agent errored,
        // the user's typed condition is still in `effectiveCondition`. Claude
        // can answer on general medical knowledge using that. This is the
        // NON-NEGOTIABLE anti-refusal clamp.
        const detectedCondition = effectiveCondition || '(none detected yet)';

        systemPrompt = `You are a senior medical research professor answering medical questions directly and substantively. The user has already accepted the decision-support disclaimer.

${audienceLine(audience)}

=== DETECTED CONDITION ===
The user appears to be asking about: **${detectedCondition}**
${dossier?.fallbackReason ? `(The disease-intake agent errored: ${dossier.fallbackReason}. Use your own medical knowledge to answer. DO NOT mention the agent or the dossier to the user.)` : ''}

PATIENT PROFILE (may be empty — that's fine):
${buildPatientContext(patient)}

${dossierInChat ? dossierInChat + '\n' : ''}${hasPriors ? priorPieces.join('\n\n') + '\n\n' : ''}=== ABSOLUTE BEHAVIOR RULES ===

1. **ANSWER THE QUESTION ON THE FIRST TURN.** Do not refuse. Do not ask for more information before answering. Do not say "I cannot..." / "I need more info to proceed" / "please provide..." / "to give you a comprehensive analysis I need...". Those responses are FAILURES.

2. If the user typed ANY disease name, abbreviation, or medical term (e.g. "RP", "LADA", "AD", "ALS", "PD", "AFib", "Retinitis Pigmentosa", "jaundice", "lupus"), IMMEDIATELY answer about that disease. Your FIRST sentence MUST confirm the condition: e.g. "**RP (Retinitis Pigmentosa)** is an inherited retinal dystrophy that..."

3. Your default chat response when the user names a disease has this shape (use markdown):

   **What it is** (1 sentence)

   **Current approved treatments**
   - bullet 1
   - bullet 2

   **Notable trials / access programs worth knowing about**
   - trial name, NCT if you know it, sponsor, what it's testing
   - any expanded-access / compassionate-use programs
   - any open-label extensions

   **Top centers / experts**
   - named centers and specialists

   **Patient resources**
   - advocacy orgs, registries

   **Red flags / common mistakes**
   - bullets

   **For a deeper personalized analysis** — prompt them: "Add this condition to the Patient Profile tab and hit Run Research for a full 16-section personalised analysis with drug-interaction checks and the live evidence pack."

4. **Bold every** drug name, trial acronym, NCT ID, percentage, center name, and advocacy org name. Use bullets. Never write a paragraph longer than 3 lines.

5. For follow-up questions (user's message isn't a disease name — e.g. "what about side effects", "tell me more about X"), use the prior analyses + dossier + general medical knowledge. Be specific and substantive.

6. When the dossier is empty or low-confidence, answer from your own clinical knowledge. Say "Based on general clinical knowledge:" as a prefix — then give the substantive answer. NEVER use low-confidence as a reason to refuse.

7. For drug interactions / contraindications / dosing for THIS patient, check their medication list and comorbidities and give specific answers.

8. Keep disclaimers short and at the END if at all. Never lead with a disclaimer.

${chatGrounding || '(No cached evidence pack this turn — that\'s OK. Answer from the dossier, prior analyses if present, and your own medical knowledge.)'}`;
        break;
      }
      case 'research':
      default:
        systemPrompt = RESEARCH_PROMPT(patient, audience) +
          (extraContext ? `\n\n${extraContext}` : '');
        break;
    }

    const messages = [
      ...chatHistory.map(m => ({ role: m.role, content: m.content })),
      {
        role: 'user',
        content: userQuery || `Please perform the ${mode} analysis now for the patient profile above.`
      }
    ];

    const response = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': apiKey,
        'anthropic-version': '2023-06-01'
      },
      body: JSON.stringify({
        model: MODEL,
        max_tokens: MAX_TOKENS,
        system: systemPrompt,
        messages
      })
    });

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      console.error('Anthropic API error:', errorData);
      return res.status(response.status).json({
        error: errorData.error?.message || 'API request failed',
        details: errorData
      });
    }

    const data = await response.json();

    // Extract Claude's text so we can feed it to the cross-validator.
    const claudeText = (data.content || [])
      .filter((c) => c?.type === 'text')
      .map((c) => c.text)
      .join('\n\n');

    // Cross-validation: fire an INDEPENDENT second AI (Perplexity / OpenAI / xAI)
    // over Claude's output + the same evidence pack to catch hallucinated
    // citations and unsupported claims. An LLM grading its own work is weak;
    // an independent second model with different training data is a much
    // stronger safeguard. Skip for pure chat mode (no structured claims to
    // audit) and when the caller opts out.
    let validation = null;
    const wantValidation = req.body?.validate !== false;
    const hasAnyValidatorKey =
      !!process.env.PERPLEXITY_API_KEY ||
      !!process.env.OPENAI_API_KEY ||
      !!process.env.XAI_API_KEY;
    if (wantValidation && mode !== 'chat' && claudeText && hasAnyValidatorKey) {
      validation = await invokeValidate({
        analysisText: claudeText,
        evidencePack: (evidence?.groundedForPrompt || []).slice(0, 18),
        patient,
        condition: patient.condition || '',
        audience
      });
    }

    return res.status(200).json({
      ...data,
      dossier: dossier
        ? {
            canonical: dossier.canonical,
            synonyms: dossier.synonyms,
            meshTerms: dossier.meshTerms,
            icd10: dossier.icd10,
            subspecialty: dossier.subspecialty,
            topCenters: dossier.topCenters || [],
            keyInvestigators: dossier.keyInvestigators || [],
            patientAdvocacy: dossier.patientAdvocacy || [],
            landmarkTrials: dossier.landmarkTrials || [],
            commonComorbidities: dossier.commonComorbidities || [],
            redFlags: dossier.redFlags || [],
            lifestyleCategories: dossier.lifestyleCategories || [],
            uncertainty: dossier.uncertainty,
            notes: dossier.notes,
            cacheHit: dossier.cacheHit,
            generatedBy: dossier.generatedBy
          }
        : null,
      evidence: evidence
        ? {
            totalUnique: evidence.totalUnique,
            accessBreakdown: evidence.accessBreakdown,
            promptPackBreakdown: evidence.promptPackBreakdown,
            qualityBreakdown: evidence.qualityBreakdown,
            knowledgeBase: evidence.knowledgeBase,
            topRanked: (evidence.topRanked || []).slice(0, 50),
            groundedForPrompt: evidence.groundedForPrompt,
            fdaLabels: evidence.fdaLabels,
            fdaManufacturers: evidence.fdaManufacturers
          }
        : null,
      trials: trials
        ? {
            total: trials.total,
            breakdown: trials.breakdown,
            subQueries: trials.subQueries,
            studies: (trials.studies || []).slice(0, 25)
          }
        : null,
      validation
    });
  } catch (error) {
    console.error('research.js error:', error);
    return res.status(500).json({ error: 'Internal server error', message: error.message });
  }
}
